name: Bug Report
description: Report a bug encountered while using One-Core-API
title: "[BUG] - Short description of the issue"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Before submitting this issue, please ensure you have:**
        *  Checked if the problem exists in [One-Core-API-Canary](https://github.com/shorthorn-project/One-Core-API-Binaries-Canary)
        *  Reviewed the existing [Issues](https://github.com/Skulltrail192/One-Core-API-Binaries/issues) to see if your problem has already been reported.
        * **If the problem exists in Canary and is not listed, please fill out the information below.**
        *  **Issues that are non-reproducible will be closed.**

  - type: checkboxes
    id: canary_check
    attributes:
      label: Verification
      description: Verify that you checked these two points before continuing
      options:
          - label: "I have checked if the issue exists in [One-Core-API-Canary](https://github.com/shorthorn-project/One-Core-API-Binaries-Canary)"
          - label: "I have checked the existing [Issues](https://github.com/Skulltrail192/One-Core-API-Binaries/issues)"
  
  - type: checkboxes
    id: canary_status
    attributes:
      label: Issue Existence in Canary
      description: Does the problem exist in the Canary build?
      options:
        - label: "The problem exists in the Canary build."
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: Concise Problem Description
      description: Briefly describe the issue you are experiencing.
      placeholder: I am experiencing issue X while doing Y, I expect Z but I'm getting A
    validations:
      required: true
  - type: dropdown
    id: system_type
    attributes:
      label: System Type
      description: Is this a physical machine or a virtual machine?
      options:
        - Physical Hardware
        - Virtual Machine
    validations:
      required: true

  - type: textarea
    id: windows_os
    attributes:
      label: Windows OS Edition
      description: Specify the Windows Operating System edition (e.g., Windows XP Professional Service Pack 3).
      placeholder: e.g. Windows XP Professional Service Pack 3
    validations:
       required: true

  - type: dropdown
    id: post_sp_updates
    attributes:
      label: Post-SP Updates Installed?
      description: Were any Post-Service Pack updates installed?
      options:
        - "Yes"
        - "No"
      default: 1
    validations:
      required: true

  - type: dropdown
    id: update_timing
    attributes:
      label: If 'Yes', specify if updates were installed...
      description: Select whether updates were before or after One-Core-API
      options:
        - "Before"
        - "After"
      default: 0
    validations:
      required: false

  - type: textarea
    id: installed_software
    attributes:
      label: Installed Software
      description: List any relevant software that might be related to the issue (e.g., Adobe Photoshop CC 2018, Firefox 132, etc.).
      placeholder: e.g. Adobe Photoshop CC 2018, Firefox 132
    validations:
      required: false

  - type: textarea
    id: hardware_specs
    attributes:
      label: Hardware Specifications
      description: "If Physical Hardware: Processor, RAM (type, amount), hard drive type, and capacity (e.g., IDE disk, 120 GB).  If Virtual Machine: Specify the virtual machine configuration details (e.g., Oracle VirtualBox 6.1.0, 2 GB RAM, 120 GB disk, AHCI mode)."
      placeholder: "e.g. Processor: Intel Core i7, RAM: 16GB DDR4, Hard Drive: 1TB SSD, OR Virtual Machine: Oracle VirtualBox 6.1.0, 2 GB RAM, 120 GB disk, AHCI mode"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce the error
      description: "Please provide a detailed step-by-step guide on how to reproduce the error."
      placeholder: "1. Do this... \n2. Then do that... \n3. And I get this issue..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Attach Relevant Logs (Optional)
      description: Please attach any logs related to the problem.
      placeholder: Attach logs here or provide a link
    validations:
        required: false
        
  - type: textarea
    id: video_recording
    attributes:
      label: Attach Video Recording (Optional)
      description: Please attach a video recording of the problem if feasible.
      placeholder: Upload video or provide a link
    validations:
        required: false